<?php

function sample_block_info() {
	$block = array();

	$block['share_this'] = array(
		'info' => t('Share this'),
		'cache' => DRUPAL_NO_CACHE
	);

	return $block;
}

function sample_block_view($delta = '') {
	$block = array();
	if ($delta == 'share_this') {
		$block['subject'] => t('Share this');
		$block['content'] => sample_share_this_block_view();		
	}

	return $block;
}

function sample_share_this_block_view() {
	$html = NULL;
	$block = NULL;

	$html = sample_share_this_block_content();

	$block = array(
		'result' => array(
			'#type' => 'markup',
			'#markup' => $html, 
			'#suffix' => '</div>',
			'#prefix' => '<div>',
		    '#attributes' => array(
		    	'class' => '',
		        'id' => 'share-this')
		    ),
			'#attachment' => array(
				'js' => array(
					'#type' => 'file',
					'#path' => '/js/share_this.js' 
				),
				'css' => array(
					'#type' => 'file',
					'#path' => '/css/share_this.css'
				),
			),
		);

	return $block;
}

function sample_share_this_block_content() {
	
}